config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions' => 'sessions#destroy'
  get 'users' => 'users#index'
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/edit' => 'users#edit', as: 'edit'
  patch 'users/:id' => 'users#update'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :name, presence: true, length: {minimum: 2}
  validates :email, presence: true, format: {with: EMAIL_REGEX}, uniqueness: true
  validates :password, presence: true, length: {minimum: 8}, if: "!password.nil?"

  before_save :email_lowercase
  def email_lowercase
    self.email.downcase!
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      redirect_to users_path
    else
      flash[:errors] = ['Invalid Email/Password Combo']
      redirect_to root_path
    end
  end
  
  def destroy
    reset_session
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "users"
  def index
    @users = User.all
  end

  def create
    user = User.new( user_params )
    if user.save
      session[:user_id] = user.id 
      redirect_to users_path
    else
      flash[:errors] = user.errors.full_messages
      redirect_to root_path
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if !params[:user][:password].blank?
      puts "NEW PASSWORD"
      if user.update( user_params )
        redirect_to user_path, id: user.id, notice: 'Password and Info Updated!'
      else
        flash[:errors] = user.errors.full_messages
        redirect_to edit_path, id: user.id 
      end
    else 
      puts "NO PASSWORD CHANGE"
      if user.update( user_params )
        redirect_to user_path, id: user.id, notice: 'Name and/or Email Updated!'
      else
        flash[:errors] = user.errors.full_messages        
        redirect_to edit_path, id: user.id 
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BcryptUsers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BcryptUsers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to 'Logout', sessions_path, method: 'delete' %>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<h1>Edit <%= @user.name %></h1>
<% if flash[:errors] %>
    <% flash[:errors].each do |e| %>
        <p><%= e %></p>
    <% end %>
<% end %>
<%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :email %>
    <%= f.text_field :email %>
<button id="password_change" type="button">Edit Password</button>
<div class="password_change" hidden>
    <%= f.label :password, 'New Password' %>
    <%= f.password_field :password %>
    <%= f.label :password_confirmation, 'New Password Confirmation' %>
    <%= f.password_field :password_confirmation %>
</div>
    <%= f.submit 'Update' %>
<% end %>
<script>
$('#password_change').click(function(){
    console.log('hey hey hey');
    $('.password_change').toggle();
    $(this).hide();
}); 
</script>
    

app/views/users/index.html.erb
<h1>All Users</h1>
<table>
    <thead>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Password</th>
        <th>Created</th>
        <th>Updated</th>
    </thead>
    <tbody>
        <% @users.each do |u| %>
        <tr>
            <td><%= u.id %></td>
            <td><%= link_to u.name, user_path(u) %></td>
            <td><%= u.email %></td>
            <td><%= u.password_digest %></td>
            <td><%= u.created_at.strftime('%c') %></td>
            <td><%= u.updated_at.strftime('%c') %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/users/show.html.erb
<h1><%= @user.name %> Show Page</h1>
<h4><%= flash[:notice] %></h4>
<%= link_to 'Edit', edit_path(@user) %>